CREATE DATABASE user; 
USE user; 
CREATE TABLE users ( 
id INT AUTO_INCREMENT PRIMARY KEY, 
user_name VARCHAR(255)NOT NULL, 
user_email VARCHAR(255) NOT NULL, 
user_password VARCHAR(255) NOT NULL 
);

